spring:
  rabbitmq:
    config:
      notificationQueue: ${NOTIFICATION_QUEUE:notification_queue}
      topicExchange: ${TOPIC_EXCHANGE:microservices_exchange}

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}