spring:
  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    host: rabbitmq-container

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka/