server:
  port: 8082

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/*/products/**,/product-service/api/*/categories/**
          filters:
            - AccessTokenFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/*/orders
          filters:
            - AccessTokenFilter

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.security: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka:password@localhost:8761/eureka/}

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
