spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  boot:
    admin:
      client:
        url: http://localhost:9091
        username: ${ADMIN_SERVER_USERNAME:admin}
        password: ${ADMIN_SERVER_PASSWORD:admin}
        enabled: true
        auto-registration: true
        instance:
          service-host-type: ip
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/*/products/**,/product-service/api/*/categories/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/*/orders

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082