spring:
  zipkin:
    base-url: http://zipkin:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservices
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka/