spring:
  zipkin:
    base-url: http://zipkin:9411
  boot:
    admin:
      client:
        url: http://admin-client:9091

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka/