---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # mysql database for order-service
  order-service-mysql:
    container_name: order-service-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: order-service
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - '3306:3306'
    volumes:
      - D:\docker-volumes\order-service-mysql:/var/lib/mysql
      - D:\docker-volumes\order-service-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # mysql database for inventory-service
  inventory-service-mysql:
    container_name: inventory-service-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inventory-service
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_TCP_PORT: 3300
    ports:
      - '3300:3300'
    expose:
      - '3300'
    volumes:
      - D:\docker-volumes\inventory-service-mysql:/var/lib/mysql
      - D:\docker-volumes\inventory-service-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # mongo database for product-service
  product-service-mongo:
    container_name: product-service-mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - D:\docker-volumes\product-service-mongo:/data/db

  # mysql database for keycloak
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:latest
    volumes:
      - D:\docker-volumes\keycloak-mysql:/var/lib/mysql
    ports:
      - '3301:3301'
    expose:
      - '3301'
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3301

  # keycloak image
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    volumes:
      - D:\docker-volumes\keycloak-data:/opt/keycloak/data/import
    depends_on:
      - keycloak-mysql

  # zipkin server
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  # discovery server
  discovery-server:
    container_name: discovery-server
    image: discovery-server:1.0.0
    ports:
      - '8761:8761'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin

  # config server
  config-server:
    container_name: config-server
    image: config-server:1.0.0
    ports:
      - '8888:8888'
    depends_on:
      - discovery-server
      - zipkin

  # api gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway/.
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: TRACE
      KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7nAsToi2PWNsjkPNIPoXIZ/O7Dt8GLBRmqUb4iWt/zNGV4WTiphiT593NRMWnD8K/wTAvaVugQn4JOqGAxV4if3lcqDTaMQuzahQcUMva9/LaqYZXNXpM2rInwjZuUOu9HtJ511gMhdhErmI1N67bV8ImzrvuYyblaRP8IrSS8vnTHSWzQHEjK4uhZ6jCHoctWF75YXrgUCkdwVwbtc3yTzjDowK7f4xKloMn7tcergvVGw+2ENMSO0SUs0MEEtceoSkhieiFZXShFcavqi89wi4VwEZ5NJ3/qasOai+LpZtP840LJEPy4T0vSdgR4Jco2QdMXbo21Eo2tEcsYX3YQIDAQAB
    depends_on:
      - zipkin
      - discovery-server
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # authentication-service
  authentication-service:
    container_name: authentication-service
    build:
      context: authentication-service/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_CLIENT_SECRET: xvBGYBwqELJ8VW1FM5KUqjQJWzUfvP24
    depends_on:
      - zipkin
      - discovery-server
      - keycloak
      - api-gateway
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # product-service
  product-service:
    container_name: product-service
    build:
      context: ./product-service/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - product-service-mongo
      - discovery-server
      - api-gateway
      - config-server
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # order-service
  order-service:
    container_name: order-service
    build:
      context: ./order-service/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - order-service-mysql
      - broker
      - zipkin
      - discovery-server
      - api-gateway
      - config-server
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # inventory-service
  inventory-service:
    container_name: inventory-service
    build:
      context: ./inventory-service/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - inventory-service-mysql
      - broker
      - zipkin
      - discovery-server
      - api-gateway
      - config-server
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # notification-service
  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway
      - config-server
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3


  # prometheus
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - D:\docker-volumes\prometheus\prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana
  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - D:\docker-volumes\grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  # elk stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: P@ssw0rd
      xpack.security.enabled: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=P@ssw0rd
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=P@ssw0rd
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./volumes/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.10
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"

    volumes:
      - ./volumes/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./volumes/filebeat/data:/usr/share/filebeat.data:rw
    user: root