spring:
  application:
    name: authentication-service
  # zipkin configuration
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9093
  servlet:
    context-path: /authentication-service
keycloak:
  realm: spring-boot-microservices
  auth-server-url: http://localhost:8180
  ssl-required: none
  resource: spring-cloud-client
  credentials:
    secret: 6d04bwRaKJVnb8LGpo6ZLRRfYvHbnIS6
  bearer-only: true
  use-resource-role-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true