eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"