spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
server:
  port: 0