spring:
  rabbitmq:
    username: admin
    password: admin
    addresses: localhost:5672
    config:
      productQueue: product_created_queue
      topicExchange: microservices_exchange
      productRoutingQueue: product_created_routing_key