server:
  port: 9804
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_URL:product-service-mongo:27017}/product-service

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    config:
      productQueue: ${PRODUCT_CREATED_QUEUE:product_created_queue}
      productRoutingQueue: ${PRODUCT_ROUTER_BINDING_KEY:product_created_routing_key}
      topicExchange: ${TOPIC_EXCHANGE:microservices_exchange}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_PROVIDER_ISSUER_URL:http://localhost:8080/realms/microservices}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka:password@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}