server:
  port: 9804
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://product-service-mongo:27017/product-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    config:
      productQueue: ${PRODUCT_CREATED_QUEUE:product_created_queue}
      productRoutingQueue: ${PRODUCT_ROUTER_BINDING_KEY:product_created_routing_key}
      topicExchange: ${TOPIC_EXCHANGE:microservices_exchange}

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always