apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server-ctr
          image: mohyehia99/discovery-server:0.0.1
          ports:
            - containerPort: 8761
          env:
            - name: DISCOVERY_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: discoveryServerHost
                  name: common-cm
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8761