spring:
  rabbitmq:
    config:
      orderQueue: ${ORDER_CREATED_QUEUE:order_created_queue}
      productQueue: ${PRODUCT_CREATED_QUEUE:product_created_queue}
      topicExchange: ${TOPIC_EXCHANGE:microservices_exchange}