server:
  port: 9801

spring:
  application:
    name: inventory-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${INVENTORY_SERVICE_DB_URL:inventory-service-mysql:3300}/inventory-service
    username: ${INVENTORY_SERVICE_DB_USERNAME:inventory-service}
    password: ${INVENTORY_SERVICE_DB_PASSWORD:P@ssw0rd}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    config:
      orderQueue: ${ORDER_CREATED_QUEUE:order_created_queue}
      productQueue: ${PRODUCT_CREATED_QUEUE:product_created_queue}
      topicExchange: ${TOPIC_EXCHANGE:microservices_exchange}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka:password@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}