spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPOSITORY}
          clone-on-start: true
          default-label: master
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    prefer-ip-address: true